### ISSUE TITLE
Haskell/Pangram readme file contradicts test file regarding non-ASCII symbols

### ISSUE THREAD

**Issue by arguapacha** [exercism/haskell#1035] opened 2021-12-30 23:57 UTC
The readme file is not in sync with the test file. It says that the input does not contain non-ASCII symbols, but the test cases include two inputs with non-ASCII symbols

Readme file:
https://github.com/exercism/haskell/blob/890b79b505f1b18adbc3b48ed4c99ef1c774c6cc/exercises/practice/pangram/.docs/instructions.md?plain=1#L9

Test file:
https://github.com/exercism/haskell/blob/890b79b505f1b18adbc3b48ed4c99ef1c774c6cc/exercises/practice/pangram/test/Tests.hs#L69

**Comment by petertseng** [comment] 2022-01-08 16:47
Duplicate of #880

**Closed by petertseng** 2022-01-08 16:47 UTC
