### ISSUE TITLE
Document with dependencies are available

### ISSUE THREAD

**Issue by hauleth** [exercism/haskell#1079] opened 2022-07-25 10:30 UTC
While trying to solve *N-th Prime* task I wanted to use 2 libraries:

- `data-ordlist` (to use `unionAll` and `minus`)
- `relude` (to use `!!?` operator)

But the task failed with error that it cannot fetch them from the repository due to lack of network connection. That is pretty obvious why there is no network in the test instance, but it makes it a little bit painful that there is no list of the libraries that are available during tasks solving.

**Comment by petertseng** [comment] 2022-07-26 01:54
duplicate of #1045

**Closed** 2022-08-12 19:52 UTC
