### ISSUE TITLE
Cabal file info not found / HttpExceptionRequest in exercises diamond and parallel-letter-frequency when running tests after submission

### ISSUE THREAD

**Issue by EspenBerget** [exercism/haskell#1006] opened 2021-10-10 07:20 UTC
The test passed on my machine, but when I submitted the code I got an error message:
```
Tests failed

Cabal file info not found for string-conversions-0.4.0.1@sha256:9c4075e54aa6cabfe244e07e2a1de720f3e98a0a6980fc671ab9c0da30f0f259,1617, updating
Selected mirror https://hackage.haskell.org/
Downloading root
HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("User-Agent","Haskell pantry package")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "hackage.haskell.org", service name: Just "443"): does not exist (Try again))
```

I search a bit and found [this](https://mail.haskell.org/pipermail/haskell-cafe/2011-August/094883.html), which could be the same issue.

**Comment by petertseng** [comment] 2021-10-20 02:20
A potential solution may make use of the `extra-deps` configuration option documented at https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps. Using the similar strategy as https://github.com/exercism/rust-test-runner/pull/27, this solution would:

* ahead of time, generate a list of commonly used packages. @ErikSchierboom, perhaps you could examine existing Haskell submissions and advise on the packages that are commonly used, so as to inform what should be in this list?
* Download (for inclusion in the test runner's image) a version of those packages, according to that list. For example, https://hackage.haskell.org/package/parallel-3.2.2.0/parallel-3.2.2.0.tar.gz seems to be the format of the download paths.
  * TBD: Does a potential solution support using multiple versions of a given package, or only one specific version? If it's only one specific version, we should be fine to use the version in the Stack resolver version that the track + test runner are currently using (efforts should be made to keep those Stack resolver versions in sync). If it's multiple versions, well of course then we'll need to figure out which versions of each package should be used.
* Place every one of those packages into the extra-deps section in stack.yaml.

Those rough solution steps may need adjustments based on how Stack and Haskell packages work. I have no particular knowledge that would give me an advantage in either, so the steps may be wrong in some details, but the overall thrust of it seems to be in the right direction.

There may also be some value in seeing whether https://github.com/ndmitchell/offline-stack and/or https://github.com/AleXoundOS/haskell-stack-mirror-script are suited to this case, but I have not put in the time to examine them and verify whether they are.

**Comment by ErikSchierboom** [comment] 2021-11-22 07:04
@petertseng Of the above list, which packages should we be pre-loading in the test runner? We probably don't want to preload them all; for Rust, we've used the top 100 most used packages.

**Comment by hraftery** [comment] 2021-11-24 16:57
FWIW, having completed 58 exercisms I found 3 (that I can recall - I can't search by "Failed") that expected additional libraries.

- [Lens Person](https://exercism.org/tracks/haskell/exercises/lens-person). Description says "you may use any library you want [including none]". I picked the common `lens` but there are others that provided lenses, including those outside hackage.
- [Parallel Letter Frequency](https://exercism.org/tracks/haskell/exercises/parallel-letter-frequency). Again, the exercise is not prescriptive on library use, but commonly one would use `parallel`.
- [Matrix](https://exercism.org/tracks/haskell/exercises/matrix). The source template provided uses `Vector` heavily so safe to assume almost everyone will want to use it.

Beyond that the list is endless. I found the restriction to bundled libraries useful for learning - modifying `package.yaml` is a lesson in itself. So I would only wish that the *expected* libraries above also be provided, and a gentle error be reported if you attempt to use more, but I can also see the appeal of trying to cast the net of "just works" a bit wider. Top 100 should satisfy many people, but then people might be coached into thinking any package is supported.

**Comment by petertseng** [comment] 2021-11-25 00:13
I do not know of a good way to determine the package that contains a module. For example, Text.ParserCombinators.ReadP is in `base`, and Text.ParserCombinators.Parsec is in `parsec`.

If we want to use the top downloaded packages, we are fortunate in that https://hackage.haskell.org/packages/top provides a list.

Of course, a solution can start small.

For example, a first solution might only add:

* `QuickCheck` (needed for dnd-character)
* `lens` (in case someone doing lens-person wants to use it)
  * perhaps other lenses libraries, but I wouldn't know. I didn't use one.
* `parallel` (parallel-letter-frequency)
* `vector` (matrix)
* `split` (note 2392 uses of Data.List.Split)

**Comment by petertseng** [comment] 2021-11-25 00:43
EBWODP: Also add:

* `random` (robot-name, simple-cipher)
* `string-conversions` (diamond - or we can see if we can rewrite the tests to not use string-conversions?)

**Comment by petertseng** [comment] 2021-11-25 03:01
Question. How is it that `hspec` currently works in the test runner? That is certainly not in there by default.

**Comment by ErikSchierboom** [comment] 2021-11-25 08:42
@petertseng The Dockerfile does a `stack build` on a pre-defined bit of code that has a dependency on the `hspec` library. See
https://github.com/exercism/haskell-test-runner/blob/main/Dockerfile#L13-L14 and https://github.com/exercism/haskell-test-runner/blob/main/pre-compiled/package.yaml#L21.

I've created a PR to add the above-mentioned dependencies: https://github.com/exercism/haskell-test-runner/pull/32
Is listing them in the `dependencies` section of the `package.yaml` enough, or do the dependencies actually need to be used in the code too?

**Comment by hraftery** [comment] 2021-11-25 10:11
I can confirm that my test run of `stack build --resolver lts-16.21 --test --no-run-tests` with just the dependencies change (no source change) does indeed detect, download and install them.

**Comment by hraftery** [comment] 2021-11-25 10:18
Keep in mind that when the PR gets merged, the user will still be none-the-wiser if they happen to add a dependency which is not part of this list, resulting in the same error message in the OP.

**Comment by ErikSchierboom** [comment] 2021-11-25 10:43
That is correct. This is something the [test runner](https://github.com/exercism/haskell-test-runner) has to support.

**Comment by ErikSchierboom** [comment] 2021-11-25 12:45
Fixed by https://github.com/exercism/haskell-test-runner/pull/32

**Comment by ErikSchierboom** [comment] 2021-11-25 13:28
> Given all packages are installed each time, people will probably notice there's a step change with no obvious cause.

Are they? The packages are downloaded and installed at build time, when the Docker container is built. It shouldn't affect the actual run time.

**Comment by hraftery** [comment] 2021-11-25 14:01
Ah, my mistake. "build time" is not triggered every time.

**Comment by petertseng** [comment] 2021-12-28 11:45
I must have forgotten to recommend the adding of `text`. We have a lot of exercises that recommend using the `text` package as an optional add-on, which is why I hadn't thought to look for it. We should add `text`, to support these following exercises.

```
$ git grep 'text.*to your list of dependencies' 
exercises/practice/acronym/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/atbash-cipher/.docs/instructions.append.md:- add `- text` to your list of dependencies in package.yaml.
exercises/practice/bob/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/diamond/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/etl/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/isogram/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/pig-latin/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/raindrops/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/resistor-color-trio/.docs/instructions.append.md:- Add `- text` to your list of dependencies in package.yaml.
exercises/practice/rotational-cipher/.docs/instructions.append.md:- add `- text` to your list of dependencies in package.yaml.
exercises/practice/twelve-days/.docs/instructions.append.md:- add `- text` to your list of dependencies in package.yaml.
```

**Comment by adql** [comment] 2021-12-30 18:48
My (earned with blood!) solution to _robot-name_ is still suffering rejection because of "missing" `random`. Which is very strange given the fix.

Is it maybe related to me starting the exercise at some time in the summer still on v2, and eventually solving it only today?

**Comment by hraftery** [comment] 2021-12-31 03:58
Hmm, I concur. I opened the exercise for the first time and used the online editor. I get:

> Could not load module ‘System.Random’
    It is a member of the hidden package ‘random-1.1’.
    Perhaps you need to add ‘random’ to the build-depends in your .cabal file.

Perhaps the fix was only good for *uninstalled* libraries, not *hidden* ones.

**Comment by adql** [comment] 2021-12-31 06:43
Yes, this is what I get as well. Then probably nothing to do with having downloaded it before.

In fact, this is similar what I got when submitting _bob_ with `Data.Text`:

> Could not load module ‘Data.Text’
It is a member of the hidden package ‘text-1.2.4.0’.
Perhaps you need to add ‘text’ to the build-depends in your .cabal file.

Which seems different from the original bug that started this issue. Interestingly, `text` wasn't added to `pre-compiled/package.yaml` in https://github.com/exercism/haskell-test-runner/pull/32. Perhaps a new bug affecting packages regardless if they were preloaded or not?

**Comment by iHiD** [comment] 2022-01-04 12:15
(cc @ErikSchierboom - Could you look into this one pls)

**Comment by ErikSchierboom** [comment] 2022-01-04 13:13
@adql I think might indeed be a new bug. I've tried adding it to the `pre-compiled/package.yaml` file. I don't know how to fix this though. Any thoughts?

**Comment by adql** [comment] 2022-01-05 12:46
@ErikSchierboom Not much of a clue, I'm not familiar with the machinery at the backend. Anyway, when I try the [haskell-test-runner](https://github.com/exercism/haskell-test-runner) locally both _bob_ and _robot-name_ pass.

How much of the exercise directory is actually uploaded to the server when running `exercism submit`? Is it only the solution file or also others such as `stack.yaml` or `<exercise>.cabal`? I've noticed that the test runner is still set to `--resolver lts-16.21`, could it be related? (if only the solution source file is uploaded, then probably not).

**Comment by ErikSchierboom** [comment] 2022-01-05 13:36
All files that are present in the exercise's directory in the track repo are checked out, with the user-submitted files overwriting any files.

**Comment by petertseng** [comment] 2022-01-08 16:41
For `robot-name`, there are a few possibilities:

* We expect that the student should submit the `package.yaml` that includes `random` under dependencies, just like how we expect that if students use any dependencies they submit `package.yaml`
* We add `random` to https://github.com/exercism/haskell/blob/main/exercises/practice/robot-name/package.yaml, presuming that every student who wants to solve this exercise will use it (you might still get something that passes the tests without using `random` if you assign IDs sequentially, though you'd sort of be going against the spirit of the tests)

for those exercises using `text`, I see that `text` has now been added, so I am now hoping that if `package.yaml` is submitted, those will work.

**Comment by adql** [comment] 2022-01-08 18:54
Ok, my bad for not having understood before that I should also submit `package.yaml` explicitly. The solutions to both _robot-name_ and _bob_ work when I do. Thanks for the help!

That said, it may be helpful to add an instruction to submit `package.yaml` where the exercise description suggests a library (as in `bob`); and/or a short comment about this under "Using packages" in [Testing on the Haskell track](https://exercism.org/docs/tracks/haskell/tests). Otherwise the student might assume (as I did) that `exercism submit xyz.hs` also automatically submits project files.

**Comment by petertseng** [comment] 2022-01-08 19:51
Absolutely correct to suggest this. https://github.com/exercism/haskell/issues/1038 created

**Comment by petertseng** [comment] 2022-01-08 19:56
and #1039

**Comment by petertseng** [comment] 2022-01-25 16:13
Here is how future items should be handled:

If the error is `Cabal file info not found for PACKAGE`, decide whether it should be added to https://github.com/exercism/haskell-test-runner/blob/main/pre-compiled/package.yaml#L11, and if the decision is favourable, add it.

If the error is of the form:

```
Could not load module ‘MODULE’
It is a member of the hidden package ‘PACKAGE’.
Perhaps you need to add ‘PACKAGE’ to the build-depends in your .cabal file.
```

then the advice in https://github.com/exercism/haskell/issues/1006#issuecomment-1008054321 applies. 

It's too much to keep talking about two different errors in the same issue, because then it's hard to tell what's relevant to what. Discussion about `robot-name` moved to https://github.com/exercism/haskell/issues/1042.

**Closed by petertseng** 2022-01-25 16:13 UTC
